export { ReactComponent as Arrow } from './arrow.svg';
export { ReactComponent as Store } from './store_icon.svg';
export { ReactComponent as Logout } from './logout_icon.svg';
export { ReactComponent as AddCategoryIcon } from './add_category_icon.svg';
export { ReactComponent as TrashCanIcon } from './trash_can_icon.svg';
export { ReactComponent as GoodsIcon } from './goods_icon.svg';
export { ReactComponent as XButton } from './X_button.svg';
export { ReactComponent as CartRemoveIcon } from './cart_remove_icon.svg';
export { ReactComponent as PlusIcon } from './plus_icon.svg';
