name: deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run scripts in server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/web-kiosk-leejooam
            git pull origin dev
            cd ~/web-kiosk-leejooam/frontend
            npm install
            npm run build
            pm2 reload client
            cd ~/web-kiosk-leejooam/backend
            npm install
            pm2 reload server
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
